### ISSUE TITLE
python train_coco_object_detection.py 报错 /  Python train_ Coco_ Object_ Detection.py reported an error

### ISSUE THREAD

**Issue by gg22mm** [JJJYmmm/Pix2SeqV2-Pytorch#1]
\Pix2SeqV2\train>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\Anaconda3\envs\mygpt\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "d:\Anaconda3\envs\mygpt\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

![图片](https://github.com/JJJYmmm/Pix2SeqV2-Pytorch/assets/6648329/91282e64-54b8-4bf1-b384-cbd9f4c19ca5)

我试了是以下两个函数不能用，不知为什么：

#A.LongestMaxSize(max_size=size, interpolation=1),
#A.PadIfNeeded(min_height=size, min_width=size, border_mode=0, value=(0,0,0)),

**Comment by gg22mm** [comment]
现在又可以了，奇怪
